More robust search for django-admin.py
The apply_djang_patches script called from ci_before_script.sh started
failing in the Travis CI build.  The reason was that django-admin.py
wasn't being found.  Try executing the script directly, instead of being
called with ``bash`` from ci_before_script.sh and try explicitly activating
the virtualenv from ``apply_django_patches``.

Addresses #626

diff --git a/scripts/apply_django_patches b/scripts/apply_django_patches
--- a/scripts/apply_django_patches
+++ b/scripts/apply_django_patches
@@ -1,4 +1,18 @@
-#!/bin/bash
+#!/usr/bin/env bash
+
+DJANGO_ADMIN=`which django-admin.py`
+if [ -z "$DJANGO_ADMIN" ]; then
+  if [ -f ~/virtualenv/python2.7/bin/activate ]; then
+    # This script assumes the virtualenv is active before running, but
+    # thsi doesn't seem to be the case when run under Travis CI. Activate
+    # the virtualenv explicitely
+    source ~/virtualenv/python2.7/bin/activate
+    DJANGO_ADMIN=`which django-admin.py`
+  else
+    echo "django-admin.py not found!"
+    exit 1
+  fi
+fi
 
 django_version()
 {
